sudo: required
language: generic

services: 
  - docker


before_install:
  - docker build -t parimalkesan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true parimalkesan/docker-react npm run test